### ISSUE TITLE
Add supplier - Email can be added without the TLD

### ISSUE THREAD

**Issue by LinkesV** [AY2425S1-CS2103T-W14-1/tp#150]
<img width="860" alt="Screenshot 2024-11-05 at 5 18 06 PM" src="https://github.com/user-attachments/assets/44a0a1e3-af4a-497f-af2f-f42282e1a931">

As seen here for the email, we can add a supplier without a top level domain name like .com or .sg. 
My solution would be to modify the regex as such that:

private static final String DOMAIN_LAST_PART_REGEX = DOMAIN_PART_REGEX + "\\.[a-zA-Z]{2,}$"; 

so that gg@gg is also disallowed

gg@gg. is already disallowed currently

**Comment by LinkesV** [comment]
Emails without a Top-Level Domain (TLD) like .com or .org (e.g., gg@gg) are uncommon in real-world email use, but they sometimes appear in:

Internal Systems: Some internal systems or intranets might allow such emails for quick, informal testing or as placeholders in a local setup, where TLDs aren’t strictly enforced.

Legacy or Custom Domains: Some organizations or old systems use custom email setups without TLDs, though this is rare today.

Localhost or Development Environments: Developers might set up emails without TLDs for local testing purposes to ensure they don’t accidentally send real emails.

Email Aliases: Some organizations or platforms can use usernames only (like user@company internally) if their email client allows it, though this usually resolves within a specific network.

In most public and commercial email systems, though, a TLD is required for valid email formats (e.g., example@domain.com)

**Comment by prave1n** [comment]
Yes, it is possible to have single character for top level domain name, however, there are currently no single character TLDs in the root.

You can see the list of TLDs that are currently in the root at this URL:

http://data.iana.org/TLD/tlds-alpha-by-domain.txt
