### ISSUE TITLE
[PE-D][Tester A] [DG] puml slightly too small

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-W14-1/tp#314]
![image.png](https://raw.githubusercontent.com/NorbertLoh/ped/main/files/1a9bfbd9-e5e5-4d7c-9641-ac1389b9001c.png)
The puml for this diagram is slightly too small and almost unreadable at 100% zoom. perhaps can make it slightly bigger

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: NorbertLoh/ped#29

**Comment by vinc3leong** [comment]
Fixed
